// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import MaskController from "./mask_controller"
application.register("mask", MaskController)

import SubmitController from "./submit_controller"
application.register("submit", SubmitController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
